baseurl = "https://koyophy.netlify.com"
title = "甲陽学院高校 物理部"
canonifyurls = true
paginate = 10
languageCode = "ja-jp"
copyright = "© 2018-2020 Koyo Physics. All Rights Reserved."
googleAnalytics = "UA-117865841-1" # delete or comment to disable Google Analytics JS generation
disqusShortname = "jia-yang-xue-yuan-wu-li-bu" #delete or comment to disable Disqus comments
hasCJKLanguage = "true"

[author]
  name = "T.H."

[related]

threshold = 80

includeNewer = false

toLower = false

[[related.indices]]
name  = "author"
toLower = true
weight = 100
[[related.indices]]
name  = "tags"
weight = 100

[params]
  DateForm = "2006/1/2"#変えるな絶対！！呪文やこれは！！
  Description = "Koyo Gakuin High School Physics Club"
  Author = "H﨑"
  email = "koyobutsuri@gmail.com"
  postSummariesFrontPage = 6 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = false #set to false to exclude read time from header of post


[[params.social]]
  title = "github"
  url = "https://github.com/koyophysics/web"
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/koyophysics"
[[params.social]]
  title = "youtube"
  url = "https://www.youtube.com/channel/UCoM7hhjA0OisVtQv2ZwlEfw"

[[menu.main]]
  name = "ホーム"
  url = "/"
  weight = -500

[[menu.main]]
  name = "活動記録"
  url = "/post/"
  weight = -400

[[menu.main]]
  name = "クラブ紹介"
  url = "/page/クラブ紹介/"
  weight = -300

[[menu.main]]
  name = "活動実績"
  url = "/page/活動実績/"
  weight = -100

[[menu.main]]
  name = "管理者ログイン"
  url = "/admin/#/"
  weight = 0
