baseurl = "https://koyophy.netlify.app"
title = "甲陽学院高校 物理部"
canonifyurls = true
paginate = 6
languageCode = "ja-jp"
hasCJKLanguage = "true"
pygmentsCodefences = true
pygmentsUseClasses = true

[related]
threshold = 80
includeNewer = false
toLower = false

[[related.indices]]
name  = "author"
toLower = true
weight = 100

[[related.indices]]
name  = "tags"
weight = 100

[permalinks]
post  = "/:section/:filename/"
page = "/:section/:filename/"
member  = "/:section/:title/"

[params]
  DateForm = "2006/1/2"
  Description = "Koyo Gakuin High School Physics Club"
  email = "koyobutsuri@gmail.com"
  postSummariesFrontPage = 6 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = false #set to false to exclude read time from header of post

[taxonomies]
  author = "authors"
  tag = "tags"

[[params.social]]
  title = "github"
  url = "https://github.com/koyophysics/web"
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/koyophysics"
[[params.social]]
  title = "youtube"
  url = "https://www.youtube.com/channel/UCoM7hhjA0OisVtQv2ZwlEfw"

[[menu.main]]
  name = "ホーム"
  url = "/"
  weight = -300

[[menu.main]]
  name = "活動記録"
  url = "/post/"
  weight = -200

[[menu.main]]
  name = "クラブ紹介"
  url = "/page/introduction/"
  weight = -100

[[menu.main]]
  name = "部誌アーカイブ"
  url = "/page/archive/"
  weight = 0
