#!/bin/sh
hugo
cp /Users/Mactaku/Documents/物理部ホームページ/web/google19dccd7c0b69f534.html /Users/Mactaku/Documents/物理部ホームページ/web/docs/google19dccd7c0b69f534.html
cp /Users/Mactaku/Documents/物理部ホームページ/web/favicon.ico /Users/Mactaku/Documents/物理部ホームページ/web/docs/favicon.ico
cp /Users/Mactaku/Documents/物理部ホームページ/web/apple-touch-icon.png /Users/Mactaku/Documents/物理部ホームページ/web/docs/apple-touch-icon.png
cp /Users/Mactaku/Documents/物理部ホームページ/web/icon-192x192.png /Users/Mactaku/Documents/物理部ホームページ/web/docs/icon-192x192.png
git add .
git commit -m "change some parts"
git push origin master
