backend:
  name: github
  repo: koyophysics/web
  branch: master

media_folder: "static/img"
publish_mode: editorial_workflow
public_folder: "/docs"

collections:
  - label: "記事" # 管理画面のサイドバーで使う
    name: "post" # 管理画面のパスで使う　例：/admin/collections/blog
    folder: "content/post" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    draft;: false
    comments: true
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開URL名", name: "slug", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime", default: "", format: "YYYY-MM-DD"}
      - {label: "サムネイル画像", name: "image", widget: "image"}
      - {label: "説明", name: "description", widget: "string"}
      - {label: "作者", name: "author", widget: "string"}
      - {label: "タグ", name: "tags", widget: "list"}
      - {label: "数式", name: "math", widget: "boolean", default: false}
      - {label: "本文", name: "body", widget: "markdown"}

  - label: "固定ページ" # 管理画面のサイドバーで使う
    name: "page" # 管理画面のパスで使う　例：/admin/collections/blog
    folder: "content/page" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    draft;: false
    comments: true
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開URL名", name: "slug", widget: "string"}
      - {label: "サムネイル画像", name: "image", widget: "image"}
      - {label: "本文", name: "body", widget: "markdown"}
